name: Build Android APK
on:
  push:
    branches: [ main ] # Dispara o build toda vez que você der push na main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout do código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🚀 Configurar Expo e EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📱 Gerar Build do APK
        run: eas build --platform android --profile preview --non-interactive
